### ISSUE TITLE
How to compile this project in Windows 

### ISSUE THREAD

**Issue by Liberations** [tidal-music/tidal-sdk-android#141]
How to compile this project in Windows 11? Is there any version other than Compose UI? For example, native Java Kotlin

**Comment by Liberations** [comment]
`dev@DESKTOP-6P0R7O6 MINGW64 /e/tidal-sdk-android (main)
$ ./generate-module.sh

Enter new module's name, using capitalized CamelCase
Example: PlaybackEngine
TidalTest

Do you want to create a module named 'TidalTest'?(y/n)y

Copying files to '/e/tidal-sdk-android/tidaltest'...
./generate-module.sh: line 38: rsync: command not found
Rename directories to 'tidaltest'...
find: warning: you have specified the global option -depth after the argument -name, but global options are not positional, i.e., -depth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
Rename keywords in files to 'TidalTest'...
Rename keywords in file name_inputs to 'tidaltest'...
Done! Module 'TidalTest' has been successfully created in '/e/tidal-sdk-android/tidaltest'.
`

**Comment by michpohl** [comment]
What exactly are you trying to do? This SDK provides functionality to build an Android app, that should be possible on a Windows machine. Compose UI is only used for the demo/test apps.

The `generate-module` script is only for engineers working on the SDK, for adding new module, so it's prrobably of no use to you. Maybe you can elaborate on what you're planning to do, then we might be able to provide some help.
